### ISSUE TITLE
Service Account credentials file not readable or invalid  

### ISSUE THREAD

**Issue by JordanProtin** [kreait/firebase-bundle#12]
## The problem

When I calling $this->container->get('firebase'), I get :
 
![Capture d’écran 2019-05-07 à 17 08 37](https://user-images.githubusercontent.com/35328504/57310821-c74ed000-70ea-11e9-8e53-9ddd9f23be61.png)

## Environment

- Symfony flex v4.2.8
- PHP Version : 7.2.15
- Firebase PHP SDK and Bundle version :
- kreait/firebase-bundle 1.2.0  
- kreait/firebase-php      4.20.1
- kreait/firebase-tokens 1.7.2 
- kreait/gcp-metadata    1.0.1

## Code to reproduce issue

My config file : 

```yaml
// %kernel.project_dir%/config/firebase/firebase.yaml
kreait_firebase:
    projects:
        default:
            public: true
            default: true
            credentials: '%kernel.project_dir%/config/packages/firebase/service_account_key.json'
            database_uri: 'https://myproject.firebaseio.com/'
            alias: 'firebase'
````

My Service Account credentials file : 

```json
// %kernel.project_dir%/config/firebase/service_account_key.json
{
  "type": "service_account",
  "project_id": "............",
  "private_key_id": "...........",
  "private_key": "...........",
  "client_email": "...........",
  "client_id": "...........",
  "auth_uri": "...........",
  "token_uri": "...........",
  "auth_provider_x509_cert_url": "...........",
  "client_x509_cert_url": "..........."
}
```

Thk's
