### ISSUE TITLE
Unable to setup bundle, json is ignored

### ISSUE THREAD

**Issue by Eldhelion** [kreait/firebase-bundle#8]
#### 1. Which version of `kreait/firebase-php` and `kreait/firebase-bundle` are you using?
"kreait/firebase-bundle": "1.0"
kreait/firebase-php ^4.0

#### 2. Which version of PHP are you using?
7.1.9

#### 3. What's the issue? and 4. Code that lead to the issue
I setup the bundle as show in the readme
my config.yml is

```
kreait_firebase:
    projects:
        first:
            public: true
            # Optional: If set to true, this project is used when
            # using Kreait\Firebase as a type hint for dependency injection
            #default: true
            credentials: '%kernel.root_dir%/config/model-firebase-adminsdk.json'
            database_uri: 'https://model.firebaseio.com/'
            alias: 'firebase'
```

The php I created more or less as done in the `app:fcm:send-message` example ( https://github.com/jeromegamez/firebase-php-examples )

```
            $messaging = $this->container->get('firebase')->getMessaging();

            $message = $message->setTitle($message->getTitle())->setBody($message->getBody());

            $responseData = $messaging->send($message);
```

But despite having indicated the path to the json in the config.yml, I'm receiving this error

```
Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "FIREBASE_CREDENTIALS" is not set.
Kreait\Firebase\ServiceAccount\Discovery\FromEnvironmentVariable: The environment variable "GOOGLE_APPLICATION_CREDENTIALS" is not set.
Kreait\Firebase\ServiceAccount\Discovery\FromGoogleWellKnownFile: The well known file is not readable or invalid
```

----
also, the doc, say that I could set default: true, but decommenting this line result in
```
InvalidConfigurationException

Unrecognized option "default" under "kreait_firebase.projects.first"
```

**Comment by jeromegamez** [comment]
Unfortunately, I am not able to reproduce the issue, I tried it by performing the following steps:

```
$ composer create-project symfony/skeleton fb-bundle-test
$ cd fb-bundle-test
$ composer require kreait/firebase-bundle
$ cp /path/to/my/credentials.json config/service_account_credentials.json
```

```yml
# config/packages/firebase.yaml
kreait_firebase:
    projects:
        first:
            default: true
            credentials: '%kernel.project_dir%/config/service_account_credentials.json'
            alias: 'firebase'
```

```php
# src/Command/AppTestCommand.php
<?php

namespace App\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class AppTestCommand extends ContainerAwareCommand
{
    protected static $defaultName = 'app:test';

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $firebase = $this->getContainer()->get('firebase');
        
        echo json_encode($firebase->getDatabase()->getRules(), true);
    }
}
```

`bin/console app:test` then returned the database rules of my projects.

- You are specifying that you're using "1.0" as a constraint for the bundle - I recommend using "^1.0" as a version constraint, this ensures that you are always on the stable release for that main version (the current release is 1.1.1). `composer show | grep kreait/firebase` will show you the currently installed versions of the `kreait/firebase-*` packages, it should look like this <img width="369" alt="composer_show" src="https://user-images.githubusercontent.com/67554/43036206-2ff9a4ea-8cfd-11e8-8138-12a21d882aee.png"> 
- If your results don't match, you could force newer versions by writing `"kreait/firebase-bundle": "^1.1.1"` in your `composer.json`
- I'm writing all this because of your notice about the dysfunctional `default` config option - this should definitely be working.

- When the Firebase PHP SDK doesn't find a credentials file at the specified location, it will try to find one by inspecting environment variables and some default locations (this is needed in Google Cloud Engine (GCE) environments. That it even tried that is an indication that it can't find or read the credentials at the location `'%kernel.root_dir%/config/model-firebase-adminsdk.json'`

I am sure you already have checked the release versions and the credentials location, but could you check again? When I tried to reproduce the issue, I wall in the trap of copying the credentials with dashes `-` but using underscores `_` in the yaml file :D
