### ISSUE TITLE
Service not found

### ISSUE THREAD

**Issue by seddighi78** [kreait/firebase-bundle#9]
## The problem
When i calling the service `kreait_firebase` or `kreait_firebase.project_name` i get: 

> You have requested a non-existent service "kreait_firebase".

## Environment
kreait/firebase-bundle               1.1.1
kreait/firebase-php                  4.16.0
kreait/firebase-tokens               1.7.1 
kreait/gcp-metadata                  1.0.1
php      7.2.7
symfony    4.1.4

## Code to reproduce issue
```
/**
     * @Route("/test")
     */
    public function test()
    {
        $firebase = $this->get('kreait_firebase');
        $title = 'test title';
        $body = 'test body';
        $token = 'my_foo_token';
        $notification = Notification::create($title, $body);
        $message = CloudMessage::withTarget('token', $token);
        $message->withNotification($notification);
        dd($firebase->getMessaging()->send($message));
    }
```

**Comment by seddighi78** [comment]
ping @jeromegamez

**Comment by jeromegamez** [comment]
I already got the notification when you created the issue, no need to ping me one minute after :).

This looks as if the Firebase bundle is not configured for your test environment. Please make sure that it either is configured separately, or that the test config imports the config file in which the bundle is configured.

**Comment by seddighi78** [comment]
Oh I'm so sorry - but I'm not in test env my app env is on dev

**Comment by jeromegamez** [comment]
Ah, I misinterpreted the environment because of the method name, my bad!

Hm... you could try debugging the service container and/or the configuration with the respective Symfony commands.

Besides that, I have no clue without seeing the whole project (but don‘t show it to me 😅)

Have you seen https://github.com/jeromegamez/firebase-php-examples ? You could compare your project/settings to this and see if you spot some differences.

**Comment by seddighi78** [comment]
Yes I see the example but it's different from the library documents my configuration file is:
```
# %kernel.project_dir%/config/packages/firebase/firebase.yaml
kreait_firebase:
    projects:
        default:
            credentials: '%kernel.project_dir%/config/packages/firebase/service_account_key.json'
            public: true
            alias: 'default'
            default: true
```
